INSERT INTO wa_region(country_iso3, code, name, fav_sort, region_center)
VALUES ('esp', 01, 'Álava', NULL, NULL)
     , ('esp', 02, 'Albacete', NULL, NULL)
     , ('esp', 03, 'Alicante', NULL, NULL)
     , ('esp', 04, 'Almería', NULL, NULL)
     , ('esp', 05, 'Ávila', NULL, NULL)
     , ('esp', 06, 'Badajoz', NULL, NULL)
     , ('esp', 07, 'Islas Baleares', NULL, NULL)
     , ('esp', 08, 'Barcelona', NULL, NULL)
     , ('esp', 09, 'Burgos', NULL, NULL)
     , ('esp', 10, 'Cáceres', NULL, NULL)
     , ('esp', 11, 'Cádiz', NULL, NULL)
     , ('esp', 12, 'Castellón', NULL, NULL)
     , ('esp', 13, 'Ciudad Real', NULL, NULL)
     , ('esp', 14, 'Córdoba', NULL, NULL)
     , ('esp', 15, 'La Coruña', NULL, NULL)
     , ('esp', 16, 'Cuenca', NULL, NULL)
     , ('esp', 17, 'Gerona', NULL, NULL)
     , ('esp', 18, 'Granada', NULL, NULL)
     , ('esp', 19, 'Guadalajara', NULL, NULL)
     , ('esp', 20, 'Guipúzcoa', NULL, NULL)
     , ('esp', 21, 'Huelva', NULL, NULL)
     , ('esp', 22, 'Huesca', NULL, NULL)
     , ('esp', 23, 'Jaén', NULL, NULL)
     , ('esp', 24, 'León', NULL, NULL)
     , ('esp', 25, 'Lérida', NULL, NULL)
     , ('esp', 26, 'La Rioja', NULL, NULL)
     , ('esp', 27, 'Lugo', NULL, NULL)
     , ('esp', 28, 'Madrid', NULL, NULL)
     , ('esp', 29, 'Málaga', NULL, NULL)
     , ('esp', 30, 'Murcia', NULL, NULL)
     , ('esp', 31, 'Navarra', NULL, NULL)
     , ('esp', 32, 'Orense', NULL, NULL)
     , ('esp', 33, 'Asturias', NULL, NULL)
     , ('esp', 34, 'Palencia', NULL, NULL)
     , ('esp', 35, 'Las Palmas', NULL, NULL)
     , ('esp', 36, 'Pontevedra', NULL, NULL)
     , ('esp', 37, 'Salamanca', NULL, NULL)
     , ('esp', 38, 'Santa Cruz de Tenerife', NULL, NULL)
     , ('esp', 39, 'Cantabria', NULL, NULL)
     , ('esp', 40, 'Segovia', NULL, NULL)
     , ('esp', 41, 'Sevilla', NULL, NULL)
     , ('esp', 42, 'Soria', NULL, NULL)
     , ('esp', 43, 'Tarragona', NULL, NULL)
     , ('esp', 44, 'Teruel', NULL, NULL)
     , ('esp', 45, 'Toledo', NULL, NULL)
     , ('esp', 46, 'Valencia', NULL, NULL)
     , ('esp', 47, 'Valladolid', NULL, NULL)
     , ('esp', 48, 'Vizcaya', NULL, NULL)
     , ('esp', 49, 'Zamora', NULL, NULL)
     , ('esp', 50, 'Zaragoza', NULL, NULL)
     , ('esp', 51, 'Ceuta', NULL, NULL)
     , ('esp', 52, 'Melilla', NULL, NULL);
